'use strict';
// @ts-check

const { test } = require('node:test');
const assert = require('node:assert/strict');
const {
  CORE_RUNTIME_SOURCE_KEYS,
  SOURCE_FILE_PATHS,
  blankStringContents,
  readSourceFile,
  readSourceFiles,
  resolveSourceFile,
  stripJsComments,
} = require('./_source-files.js');

test('source file facade records the script-tag runtime source tail', () => {
  assert.deepEqual(CORE_RUNTIME_SOURCE_KEYS, ['content', 'entitiesSpawnModifiers', 'entities', 'entitiesCombatEffects', 'entitiesDeferredSpawns', 'entitiesShockPulse', 'render', 'game']);
  assert.equal(SOURCE_FILE_PATHS.contentTerminals.replaceAll('\\', '/'), 'src/content/terminals.js');
  assert.equal(SOURCE_FILE_PATHS.contentWeapons.replaceAll('\\', '/'), 'src/content/weapons.js');
  assert.equal(SOURCE_FILE_PATHS.contentUpgrades.replaceAll('\\', '/'), 'src/content/upgrades.js');
  assert.equal(SOURCE_FILE_PATHS.contentPickups.replaceAll('\\', '/'), 'src/content/pickups.js');
  assert.equal(SOURCE_FILE_PATHS.contentProjectiles.replaceAll('\\', '/'), 'src/content/projectiles.js');
  assert.equal(SOURCE_FILE_PATHS.contentMusic.replaceAll('\\', '/'), 'src/content/music.js');
  assert.equal(SOURCE_FILE_PATHS.contentModifiers.replaceAll('\\', '/'), 'src/content/modifiers.js');
  assert.equal(SOURCE_FILE_PATHS.contentMetaSave.replaceAll('\\', '/'), 'src/content/meta-save.js');
  assert.equal(SOURCE_FILE_PATHS.contentCombo.replaceAll('\\', '/'), 'src/content/combo.js');
  assert.equal(SOURCE_FILE_PATHS.contentEvents.replaceAll('\\', '/'), 'src/content/events.js');
  assert.equal(SOURCE_FILE_PATHS.contentShop.replaceAll('\\', '/'), 'src/content/shop.js');
  assert.equal(SOURCE_FILE_PATHS.contentPerks.replaceAll('\\', '/'), 'src/content/perks.js');
  assert.equal(SOURCE_FILE_PATHS.contentEffects.replaceAll('\\', '/'), 'src/content/effects.js');
  assert.equal(SOURCE_FILE_PATHS.contentHackware.replaceAll('\\', '/'), 'src/content/hackware.js');
  assert.equal(SOURCE_FILE_PATHS.contentStatus.replaceAll('\\', '/'), 'src/content/status.js');
  assert.equal(SOURCE_FILE_PATHS.contentLighting.replaceAll('\\', '/'), 'src/content/lighting.js');
  assert.equal(SOURCE_FILE_PATHS.contentFloorGenerator.replaceAll('\\', '/'), 'src/content/floor-generator.js');
  assert.equal(SOURCE_FILE_PATHS.content.replaceAll('\\', '/'), 'src/content.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesSourceMetadata.replaceAll('\\', '/'), 'src/entities/source-metadata.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesSpawnTable.replaceAll('\\', '/'), 'src/entities/spawn-table.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesEnemyStats.replaceAll('\\', '/'), 'src/entities/enemy-stats.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesEnemyClassification.replaceAll('\\', '/'), 'src/entities/enemy-classification.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesSpawnModifiers.replaceAll('\\', '/'), 'src/entities/spawn-modifiers.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesRoomIndex.replaceAll('\\', '/'), 'src/entities/room-index.js');
  assert.equal(SOURCE_FILE_PATHS.entities.replaceAll('\\', '/'), 'src/entities.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesEliteAffixes.replaceAll('\\', '/'), 'src/entities/elite-affixes.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesStatusEffects.replaceAll('\\', '/'), 'src/entities/status-effects.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesAiHelpers.replaceAll('\\', '/'), 'src/entities/ai-helpers.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesArchitectWalls.replaceAll('\\', '/'), 'src/entities/architect-walls.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesBeacons.replaceAll('\\', '/'), 'src/entities/beacons.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesCrates.replaceAll('\\', '/'), 'src/entities/crates.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesMines.replaceAll('\\', '/'), 'src/entities/mines.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesShieldGenerators.replaceAll('\\', '/'), 'src/entities/shield-generators.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesSecuritySystems.replaceAll('\\', '/'), 'src/entities/security-systems.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesWallTurrets.replaceAll('\\', '/'), 'src/entities/wall-turrets.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesFieldEffects.replaceAll('\\', '/'), 'src/entities/field-effects.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesDeathHooks.replaceAll('\\', '/'), 'src/entities/death-hooks.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesFuseShards.replaceAll('\\', '/'), 'src/entities/fuse-shards.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesRenderPasses.replaceAll('\\', '/'), 'src/entities/render-passes.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesVolatileCores.replaceAll('\\', '/'), 'src/entities/volatile-cores.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesCombatEffects.replaceAll('\\', '/'), 'src/entities/combat-effects.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesDeferredSpawns.replaceAll('\\', '/'), 'src/entities/deferred-spawns.js');
  assert.equal(SOURCE_FILE_PATHS.entitiesShockPulse.replaceAll('\\', '/'), 'src/entities/shock-pulse.js');
  assert.equal(SOURCE_FILE_PATHS.render.replaceAll('\\', '/'), 'src/render.js');
  assert.equal(SOURCE_FILE_PATHS.game.replaceAll('\\', '/'), 'src/game.js');
});

test('source file facade resolves and loads core runtime sources', () => {
  assert.equal(resolveSourceFile(__dirname, 'content').endsWith('src/content.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentTerminals').endsWith('src/content/terminals.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentWeapons').endsWith('src/content/weapons.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentUpgrades').endsWith('src/content/upgrades.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentPickups').endsWith('src/content/pickups.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentProjectiles').endsWith('src/content/projectiles.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentMusic').endsWith('src/content/music.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentModifiers').endsWith('src/content/modifiers.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentMetaSave').endsWith('src/content/meta-save.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentCombo').endsWith('src/content/combo.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentEvents').endsWith('src/content/events.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentShop').endsWith('src/content/shop.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentPerks').endsWith('src/content/perks.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentEffects').endsWith('src/content/effects.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentHackware').endsWith('src/content/hackware.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentStatus').endsWith('src/content/status.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentLighting').endsWith('src/content/lighting.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'contentFloorGenerator').endsWith('src/content/floor-generator.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesSourceMetadata').endsWith('src/entities/source-metadata.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesSpawnTable').endsWith('src/entities/spawn-table.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesEnemyStats').endsWith('src/entities/enemy-stats.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesEnemyClassification').endsWith('src/entities/enemy-classification.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesSpawnModifiers').endsWith('src/entities/spawn-modifiers.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesRoomIndex').endsWith('src/entities/room-index.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesEliteAffixes').endsWith('src/entities/elite-affixes.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesStatusEffects').endsWith('src/entities/status-effects.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesAiHelpers').endsWith('src/entities/ai-helpers.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesArchitectWalls').endsWith('src/entities/architect-walls.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesBeacons').endsWith('src/entities/beacons.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesCrates').endsWith('src/entities/crates.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesMines').endsWith('src/entities/mines.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesShieldGenerators').endsWith('src/entities/shield-generators.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesSecuritySystems').endsWith('src/entities/security-systems.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesWallTurrets').endsWith('src/entities/wall-turrets.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesFieldEffects').endsWith('src/entities/field-effects.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesDeathHooks').endsWith('src/entities/death-hooks.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesFuseShards').endsWith('src/entities/fuse-shards.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesRenderPasses').endsWith('src/entities/render-passes.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesVolatileCores').endsWith('src/entities/volatile-cores.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesCombatEffects').endsWith('src/entities/combat-effects.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesDeferredSpawns').endsWith('src/entities/deferred-spawns.js'), true);
  assert.equal(resolveSourceFile(__dirname, 'entitiesShockPulse').endsWith('src/entities/shock-pulse.js'), true);
  const sources = readSourceFiles(__dirname);
  const terminalSource = readSourceFile(__dirname, 'contentTerminals');
  const weaponSource = readSourceFile(__dirname, 'contentWeapons');
  const upgradeSource = readSourceFile(__dirname, 'contentUpgrades');
  const pickupSource = readSourceFile(__dirname, 'contentPickups');
  const projectileSource = readSourceFile(__dirname, 'contentProjectiles');
  const musicSource = readSourceFile(__dirname, 'contentMusic');
  const modifierSource = readSourceFile(__dirname, 'contentModifiers');
  const metaSaveSource = readSourceFile(__dirname, 'contentMetaSave');
  const comboSource = readSourceFile(__dirname, 'contentCombo');
  const eventSource = readSourceFile(__dirname, 'contentEvents');
  const shopSource = readSourceFile(__dirname, 'contentShop');
  const perkSource = readSourceFile(__dirname, 'contentPerks');
  const effectsSource = readSourceFile(__dirname, 'contentEffects');
  const hackwareSource = readSourceFile(__dirname, 'contentHackware');
  const statusSource = readSourceFile(__dirname, 'contentStatus');
  const lightingSource = readSourceFile(__dirname, 'contentLighting');
  const floorGeneratorSource = readSourceFile(__dirname, 'contentFloorGenerator');
  const sourceMetadataSource = readSourceFile(__dirname, 'entitiesSourceMetadata');
  const spawnTableSource = readSourceFile(__dirname, 'entitiesSpawnTable');
  const enemyStatsSource = readSourceFile(__dirname, 'entitiesEnemyStats');
  const enemyClassificationSource = readSourceFile(__dirname, 'entitiesEnemyClassification');
  const spawnModifierSource = readSourceFile(__dirname, 'entitiesSpawnModifiers');
  const entitySource = readSourceFile(__dirname, 'entities');
  const roomIndexSource = readSourceFile(__dirname, 'entitiesRoomIndex');
  const eliteAffixSource = readSourceFile(__dirname, 'entitiesEliteAffixes');
  const statusEffectSource = readSourceFile(__dirname, 'entitiesStatusEffects');
  const aiHelperSource = readSourceFile(__dirname, 'entitiesAiHelpers');
  const architectWallSource = readSourceFile(__dirname, 'entitiesArchitectWalls');
  const beaconSource = readSourceFile(__dirname, 'entitiesBeacons');
  const crateSource = readSourceFile(__dirname, 'entitiesCrates');
  const mineSource = readSourceFile(__dirname, 'entitiesMines');
  const shieldGeneratorSource = readSourceFile(__dirname, 'entitiesShieldGenerators');
  const securitySystemSource = readSourceFile(__dirname, 'entitiesSecuritySystems');
  const wallTurretSource = readSourceFile(__dirname, 'entitiesWallTurrets');
  const fieldEffectSource = readSourceFile(__dirname, 'entitiesFieldEffects');
  const deathHookSource = readSourceFile(__dirname, 'entitiesDeathHooks');
  const fuseShardSource = readSourceFile(__dirname, 'entitiesFuseShards');
  const renderPassSource = readSourceFile(__dirname, 'entitiesRenderPasses');
  const volatileCoreSource = readSourceFile(__dirname, 'entitiesVolatileCores');
  const combatEffectSource = readSourceFile(__dirname, 'entitiesCombatEffects');
  const deferredSpawnSource = readSourceFile(__dirname, 'entitiesDeferredSpawns');
  const shockPulseSource = readSourceFile(__dirname, 'entitiesShockPulse');
  assert.match(terminalSource, /const\s+LORE_ENTRIES\s*=\s*\[/);
  assert.match(weaponSource, /const\s+WEAPON_AFFIXES\s*=\s*\{/);
  assert.match(upgradeSource, /const\s+UPGRADES\s*=\s*\[/);
  assert.match(upgradeSource, /const\s+AUGMENTS\s*=\s*\{/);
  assert.match(pickupSource, /class\s+Item\b/);
  assert.match(pickupSource, /class\s+WeaponCacheItem\b/);
  assert.match(pickupSource, /const\s+ITEM_TYPES\s*=/);
  assert.match(pickupSource, /function\s+pickItemType\s*\(/);
  assert.match(pickupSource, /function\s+rollSecretWeaponCacheWeapon\s*\(/);
  assert.match(projectileSource, /class\s+Projectile\b/);
  assert.match(projectileSource, /function\s+detonateGrenade\s*\(/);
  assert.match(musicSource, /const\s+music\s*=\s*\(\(\)\s*=>\s*\{/);
  assert.match(musicSource, /function\s+tryPlayTitle\s*\(/);
  assert.match(modifierSource, /const\s+DIFFICULTIES\s*=\s*\{/);
  assert.match(modifierSource, /const\s+FLOOR_MODIFIERS\s*=\s*\{/);
  assert.match(metaSaveSource, /const\s+META_UPGRADES\s*=/);
  assert.match(metaSaveSource, /function\s+loadMeta\s*\(/);
  assert.match(comboSource, /const\s+combo\s*=\s*\{/);
  assert.match(comboSource, /function\s+registerKill\s*\(/);
  assert.match(eventSource, /const\s+EVENTS\s*=\s*\[/);
  assert.match(eventSource, /function\s+applyEventEffect\s*\(/);
  assert.match(shopSource, /const\s+SHOP_PRICES\s*=\s*\{/);
  assert.match(shopSource, /function\s+generateShopItems\s*\(/);
  assert.match(perkSource, /const\s+PERK_POOL\s*=\s*\{/);
  assert.match(perkSource, /function\s+rollPerkChoices\s*\(/);
  assert.match(effectsSource, /function\s+spawnParticles\s*\(/);
  assert.match(effectsSource, /function\s+spawnDmgText\s*\(/);
  assert.match(hackwareSource, /const\s+HACKWARE\s*=\s*\{/);
  assert.match(hackwareSource, /function\s+activateHackware\s*\(/);
  assert.match(statusSource, /function\s+getStatusEffects\s*\(/);
  assert.match(statusSource, /function\s+drawStatusBar\s*\(/);
  assert.match(lightingSource, /function\s+updateLighting\s*\(/);
  assert.match(lightingSource, /function\s+tileHasLOS\s*\(/);
  assert.match(floorGeneratorSource, /function\s+generateFloor\s*\(/);
  assert.match(floorGeneratorSource, /function\s+resolvePreferredSpawnRoom\s*\(/);
  assert.match(sourceMetadataSource, /const\s+CREDIT_VALUES\s*=\s*\{/);
  assert.match(sourceMetadataSource, /const\s+SOURCE_LABELS\s*=\s*\{/);
  assert.match(sourceMetadataSource, /const\s+SOURCE_COLOURS\s*=\s*\{/);
  assert.match(sourceMetadataSource, /function\s+sourceLabel\s*\(/);
  assert.match(sourceMetadataSource, /function\s+sourceColour\s*\(/);
  assert.match(sourceMetadataSource, /const\s+BOSS_NAMES\s*=\s*\{/);
  assert.match(sourceMetadataSource, /const\s+BOSS_PHASE_MARKS\s*=\s*\{/);
  assert.match(sourceMetadataSource, /function\s+getBossPhaseMarks\s*\(/);
  assert.match(spawnTableSource, /const\s+ENEMY_WEIGHTS\s*=\s*\{/);
  assert.match(spawnTableSource, /const\s+ENEMY_TYPES_LIST\s*=\s*Object\.keys\(ENEMY_WEIGHTS\)/);
  assert.match(spawnTableSource, /function\s+pickEnemyType\s*\(/);
  assert.match(enemyStatsSource, /const\s+ENEMY_BASE_STATS\s*=\s*\{/);
  assert.match(enemyStatsSource, /function\s+getEnemyBaseStats\s*\(/);
  assert.match(enemyClassificationSource, /const\s+BOSS_TYPES\s*=\s*new Set\(/);
  assert.match(enemyClassificationSource, /const\s+ELITE_EXCLUDED_TYPES\s*=\s*new Set\(/);
  assert.match(enemyClassificationSource, /const\s+GHOSTABLE_TYPES\s*=\s*new Set\(/);
  assert.match(enemyClassificationSource, /function\s+isBossEnemyType\s*\(/);
  assert.match(enemyClassificationSource, /function\s+canRollEliteEnemyType\s*\(/);
  assert.match(enemyClassificationSource, /function\s+isGhostableEnemyType\s*\(/);
  assert.match(spawnModifierSource, /function\s+scaleEnemySpawnHpForModifier\s*\(/);
  assert.match(spawnModifierSource, /function\s+applyEliteSpawnRoll\s*\(/);
  assert.match(spawnModifierSource, /allowElite[\s\S]{0,240}canRollEliteEnemyType\(type\)/);
  assert.match(roomIndexSource, /const\s+enemiesByRoom\s*=\s*new Map\(\)/);
  assert.match(roomIndexSource, /function\s+enemiesInRoomIter\s*\(/);
  assert.match(eliteAffixSource, /function\s+tickEliteAffix\s*\(/);
  assert.match(eliteAffixSource, /function\s+notifyFrenzyElites\s*\(/);
  assert.match(eliteAffixSource, /function\s+notifyPredatorElites\s*\(/);
  assert.match(statusEffectSource, /function\s+tickEnemyStatusEffects\s*\(/);
  assert.match(aiHelperSource, /function\s+isInsideCone\s*\(/);
  assert.match(aiHelperSource, /function\s+getPositionAgoFromHistory\s*\(/);
  assert.match(aiHelperSource, /function\s+predictFromHistory\s*\(/);
  assert.match(aiHelperSource, /function\s+pickMirrorKinematics\s*\(/);
  assert.match(aiHelperSource, /function\s+magnetonBendDir\s*\(/);
  assert.match(architectWallSource, /function\s+pickArchitectTarget\s*\(/);
  assert.match(architectWallSource, /function\s+_isTileOccupiedByActor\s*\(/);
  assert.match(architectWallSource, /function\s+updatePlacedWalls\s*\(/);
  assert.match(beaconSource, /const\s+BEACON_COUNTDOWN\s*=/);
  assert.match(beaconSource, /function\s+createBeacon\s*\(/);
  assert.match(beaconSource, /function\s+damageBeacon\s*\(/);
  assert.match(beaconSource, /function\s+destroyBeacon\s*\(/);
  assert.match(beaconSource, /function\s+damageBeaconsInRadius\s*\(/);
  assert.match(beaconSource, /function\s+updateBeacons\s*\(/);
  assert.match(beaconSource, /function\s+drawBeacons\s*\(/);
  assert.match(crateSource, /function\s+createCrate\s*\(/);
  assert.match(crateSource, /function\s+getCrateAt\s*\(/);
  assert.match(crateSource, /function\s+damageCrate\s*\(/);
  assert.match(crateSource, /function\s+destroyCrate\s*\(/);
  assert.match(crateSource, /function\s+damageCrateAtTile\s*\(/);
  assert.match(crateSource, /function\s+damageCratesInRadius\s*\(/);
  assert.match(mineSource, /const\s+MINE_TRIGGER_RADIUS\s*=/);
  assert.match(mineSource, /const\s+MINE_FUSE_SHOT\s*=/);
  assert.match(mineSource, /function\s+createMine\s*\(/);
  assert.match(mineSource, /function\s+armMine\s*\(/);
  assert.match(mineSource, /function\s+detonateMine\s*\(/);
  assert.match(mineSource, /function\s+triggerMinesInRadius\s*\(/);
  assert.match(mineSource, /function\s+updateMines\s*\(/);
  assert.match(mineSource, /function\s+drawMines\s*\(/);
  assert.match(shieldGeneratorSource, /const\s+SHIELD_GEN_DR\s*=/);
  assert.match(shieldGeneratorSource, /function\s+createShieldGen\s*\(/);
  assert.match(shieldGeneratorSource, /function\s+damageShieldGen\s*\(/);
  assert.match(shieldGeneratorSource, /function\s+destroyShieldGen\s*\(/);
  assert.match(shieldGeneratorSource, /function\s+damageShieldGensInRadius\s*\(/);
  assert.match(shieldGeneratorSource, /function\s+isEnemyShieldGenProtected\s*\(/);
  assert.match(shieldGeneratorSource, /function\s+updateShieldGens\s*\(/);
  assert.match(shieldGeneratorSource, /function\s+drawShieldGens\s*\(/);
  assert.match(securitySystemSource, /const\s+CAMERA_CONE_HALF\s*=/);
  assert.match(securitySystemSource, /function\s+createCamera\s*\(/);
  assert.match(securitySystemSource, /function\s+damageCamera\s*\(/);
  assert.match(securitySystemSource, /function\s+damageCamerasInRadius\s*\(/);
  assert.match(securitySystemSource, /function\s+updateCameras\s*\(/);
  assert.match(securitySystemSource, /function\s+drawCameras\s*\(/);
  assert.match(securitySystemSource, /const\s+LASER_HIT_CD\s*=/);
  assert.match(securitySystemSource, /const\s+LASER_DISABLE_DUR\s*=/);
  assert.match(securitySystemSource, /function\s+createLaser\s*\(/);
  assert.match(securitySystemSource, /function\s+damageLaserEmitter\s*\(/);
  assert.match(securitySystemSource, /function\s+damageLasersInRadius\s*\(/);
  assert.match(securitySystemSource, /function\s+updateLasers\s*\(/);
  assert.match(securitySystemSource, /function\s+drawLasers\s*\(/);
  assert.match(wallTurretSource, /const\s+WTURRET_RANGE_HOSTILE\s*=/);
  assert.match(wallTurretSource, /function\s+createWallTurret\s*\(/);
  assert.match(wallTurretSource, /function\s+wallTurretDmg\s*\(/);
  assert.match(wallTurretSource, /function\s+damageWallTurret\s*\(/);
  assert.match(wallTurretSource, /function\s+destroyWallTurret\s*\(/);
  assert.match(wallTurretSource, /function\s+hackWallTurret\s*\(/);
  assert.match(wallTurretSource, /function\s+damageWallTurretsInRadius\s*\(/);
  assert.match(wallTurretSource, /function\s+updateWallTurrets\s*\(/);
  assert.match(wallTurretSource, /function\s+drawWallTurrets\s*\(/);
  assert.match(fieldEffectSource, /const\s+disruptionFields\s*=\s*\[\]/);
  assert.match(fieldEffectSource, /const\s+gravityWells\s*=\s*\[\]/);
  assert.match(fieldEffectSource, /const\s+frostPatches\s*=\s*\[\]/);
  assert.match(fieldEffectSource, /function\s+updateDisruptionFields\s*\(/);
  assert.match(fieldEffectSource, /function\s+drawDisruptionFields\s*\(/);
  assert.match(fieldEffectSource, /function\s+isPlayerInNullifierAura\s*\(/);
  assert.match(fieldEffectSource, /function\s+updateNullifierJam\s*\(/);
  assert.match(fieldEffectSource, /function\s+updateFrostPatches\s*\(/);
  assert.match(fieldEffectSource, /function\s+drawFrostPatches\s*\(/);
  assert.match(fieldEffectSource, /function\s+updateGravityWells\s*\(/);
  assert.match(fieldEffectSource, /function\s+drawGravityWells\s*\(/);
  assert.match(deathHookSource, /function\s+notifyGhostProjectors\s*\(/);
  assert.match(deathHookSource, /function\s+notifyVengeance\s*\(/);
  assert.match(fuseShardSource, /class\s+FuseShard\b/);
  assert.match(fuseShardSource, /function\s+_detonateBombAt\s*\(/);
  assert.match(renderPassSource, /function\s+drawReaperPlayerRings\s*\(/);
  assert.match(renderPassSource, /function\s+drawTetherLeashes\s*\(/);
  assert.match(volatileCoreSource, /function\s+createVCore\s*\(/);
  assert.match(volatileCoreSource, /function\s+primeVCoresInRadius\s*\(/);
  assert.match(volatileCoreSource, /function\s+updateVCores\s*\(/);
  assert.match(volatileCoreSource, /function\s+drawVCores\s*\(/);
  assert.match(combatEffectSource, /function\s+_applyStunOnlyEffects\s*\(/);
  assert.match(combatEffectSource, /function\s+applyHitEffects\s*\(/);
  assert.match(combatEffectSource, /function\s+applyOnKill\s*\(/);
  assert.match(deferredSpawnSource, /const\s+pendingEnemySpawns\s*=\s*\[\]/);
  assert.match(deferredSpawnSource, /function\s+spawnGhost\s*\(/);
  assert.match(shockPulseSource, /function\s+triggerShockPulse\s*\(/);
  assert.doesNotMatch(sources.content, /function\s+spawnParticles\s*\(/);
  assert.doesNotMatch(sources.content, /const\s+ambientParticles\s*=/);
  assert.doesNotMatch(sources.content, /function\s+activateHackware\s*\(/);
  assert.doesNotMatch(sources.content, /function\s+registerKill\s*\(/);
  assert.doesNotMatch(sources.content, /function\s+getStatusEffects\s*\(/);
  assert.doesNotMatch(sources.content, /function\s+loadMeta\s*\(/);
  assert.doesNotMatch(sources.content, /function\s+updateLighting\s*\(/);
  assert.doesNotMatch(sources.content, /function\s+pickItemType\s*\(/);
  assert.doesNotMatch(sources.content, /function\s+rollSecretWeaponCacheWeapon\s*\(/);
  assert.doesNotMatch(sources.content, /function\s+generateFloor\s*\(/);
  assert.match(sources.entities, /class\s+Player\b/);
  assert.doesNotMatch(sources.entities, /const\s+enemiesByRoom\s*=\s*new Map\(\)/);
  assert.doesNotMatch(sources.entities, /function\s+tickEliteAffix\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+notifyFrenzyElites\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+notifyPredatorElites\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+tickEnemyStatusEffects\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+isInsideCone\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+getPositionAgoFromHistory\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+predictFromHistory\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+pickMirrorKinematics\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+magnetonBendDir\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+pickArchitectTarget\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+_isTileOccupiedByActor\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updatePlacedWalls\s*\(/);
  assert.doesNotMatch(sources.entities, /const\s+BEACON_COUNTDOWN\s*=/);
  assert.doesNotMatch(sources.entities, /function\s+createBeacon\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageBeacon\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+destroyBeacon\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageBeaconsInRadius\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateBeacons\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawBeacons\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+createCrate\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+getCrateAt\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageCrate\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+destroyCrate\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageCrateAtTile\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageCratesInRadius\s*\(/);
  assert.doesNotMatch(sources.entities, /const\s+MINE_TRIGGER_RADIUS\s*=/);
  assert.doesNotMatch(sources.entities, /const\s+MINE_FUSE_SHOT\s*=/);
  assert.doesNotMatch(sources.entities, /function\s+createMine\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+armMine\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+detonateMine\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+triggerMinesInRadius\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateMines\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawMines\s*\(/);
  assert.doesNotMatch(sources.entities, /const\s+SHIELD_GEN_DR\s*=/);
  assert.doesNotMatch(sources.entities, /function\s+createShieldGen\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageShieldGen\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+destroyShieldGen\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageShieldGensInRadius\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+isEnemyShieldGenProtected\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateShieldGens\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawShieldGens\s*\(/);
  assert.doesNotMatch(sources.entities, /const\s+CAMERA_CONE_HALF\s*=/);
  assert.doesNotMatch(sources.entities, /function\s+createCamera\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageCamera\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageCamerasInRadius\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateCameras\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawCameras\s*\(/);
  assert.doesNotMatch(sources.entities, /const\s+LASER_HIT_CD\s*=/);
  assert.doesNotMatch(sources.entities, /const\s+LASER_DISABLE_DUR\s*=/);
  assert.doesNotMatch(sources.entities, /function\s+createLaser\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageLaserEmitter\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageLasersInRadius\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateLasers\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawLasers\s*\(/);
  assert.doesNotMatch(sources.entities, /const\s+WTURRET_RANGE_HOSTILE\s*=/);
  assert.doesNotMatch(sources.entities, /function\s+createWallTurret\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+wallTurretDmg\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageWallTurret\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+destroyWallTurret\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+hackWallTurret\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+damageWallTurretsInRadius\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateWallTurrets\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawWallTurrets\s*\(/);
  assert.doesNotMatch(sources.entities, /const\s+disruptionFields\s*=\s*\[\]/);
  assert.doesNotMatch(sources.entities, /const\s+gravityWells\s*=\s*\[\]/);
  assert.doesNotMatch(sources.entities, /const\s+frostPatches\s*=\s*\[\]/);
  assert.doesNotMatch(sources.entities, /function\s+updateDisruptionFields\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawDisruptionFields\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+isPlayerInNullifierAura\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateNullifierJam\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateFrostPatches\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawFrostPatches\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateGravityWells\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawGravityWells\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+notifyGhostProjectors\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+notifyVengeance\s*\(/);
  assert.doesNotMatch(sources.entities, /class\s+FuseShard\b/);
  assert.doesNotMatch(sources.entities, /function\s+drawReaperPlayerRings\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawTetherLeashes\s*\(/);
  assert.doesNotMatch(sources.entities, /const\s+GHOSTABLE_TYPES\s*=\s*new Set\(/);
  assert.doesNotMatch(sources.entities, /function\s+createVCore\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+primeVCoresInRadius\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+detonateVCore\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+updateVCores\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+drawVCores\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+_applyStunOnlyEffects\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+applyHitEffects\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+applyOnKill\s*\(/);
  assert.doesNotMatch(sources.entities, /const\s+pendingEnemySpawns\s*=\s*\[\]/);
  assert.doesNotMatch(sources.entities, /function\s+spawnGhost\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+triggerShockPulse\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+scaleEnemySpawnHpForModifier\s*\(/);
  assert.doesNotMatch(sources.entities, /function\s+applyEliteSpawnRoll\s*\(/);
  assert.match(sources.entitiesSpawnModifiers, /function\s+scaleEnemySpawnHpForModifier\s*\(/);
  assert.match(sources.entitiesSpawnModifiers, /function\s+applyEliteSpawnRoll\s*\(/);
  assert.match(sources.entitiesCombatEffects, /function\s+_applyStunOnlyEffects\s*\(/);
  assert.match(sources.entitiesCombatEffects, /function\s+applyHitEffects\s*\(/);
  assert.match(sources.entitiesCombatEffects, /function\s+applyOnKill\s*\(/);
  assert.match(sources.entitiesDeferredSpawns, /const\s+pendingEnemySpawns\s*=\s*\[\]/);
  assert.match(sources.entitiesDeferredSpawns, /function\s+spawnGhost\s*\(/);
  assert.match(sources.entitiesShockPulse, /function\s+triggerShockPulse\s*\(/);
  assert.match(sources.render, /function\s+drawWorld\s*\(/);
  assert.match(sources.game, /const\s+game\s*=/);
});

test('source file facade rejects unknown keys loudly', () => {
  assert.throws(
    // @ts-expect-error exercising runtime validation.
    () => readSourceFile(__dirname, 'contents'),
    /Unknown source file key: contents/
  );
});

test('stripJsComments preserves comment-like text in strings and regex literals', () => {
  const source = [
    "const url = 'https://example.test/path'; // remove line comment",
    'const re = /\\/\\/ not a comment/;',
    'function f(x) { return /[/*]/.test(x); }',
    'function g(ok, x) { if (ok) /[/*]/.test(x); return 1; }',
    '/* remove block comment',
    '   but preserve its newline */',
    'const done = true;',
  ].join('\n');

  const stripped = stripJsComments(source);
  assert.match(stripped, /https:\/\/example\.test\/path/);
  assert.match(stripped, /\/\\\/\\\/ not a comment\//);
  assert.match(stripped, /return \/\[\/\*\]\/\.test\(x\);/);
  assert.match(stripped, /if \(ok\) \/\[\/\*\]\/\.test\(x\);/);
  assert.doesNotMatch(stripped, /remove line comment/);
  assert.doesNotMatch(stripped, /remove block comment/);
  assert.match(stripped, /const done = true;/);
});

test('blankStringContents preserves string length and quote delimiters', () => {
  const src = "const value = 'a { tricky } string';";
  const blanked = blankStringContents(src);
  assert.equal(blanked.length, src.length);
  assert.match(blanked, /'                   '/);
  assert.doesNotMatch(blanked, /tricky/);
});
