'use strict';

// Browser script order is producer-before-consumer and must match index.html.
// Keep engine primitives first, followed by game data/meta modules, dungeon
// helpers, then the large runtime coordinators that consume those globals.
const requiredInIndex = [
  './src/neon.js',
  './src/game-states.js',
  './engine/math.js',
  './engine/viewport.js',
  './engine/audio.js',
  './engine/input.js',
  './engine/touch.js',
  './engine/draw.js',
  './engine/decor.js',
  './engine/particles.js',
  './engine/minimap.js',
  './src/platform.js',
  './engine/biomes.js',
  './src/data/biomes.js',
  './src/data/palettes.js',
  './src/data/logs.js',
  './src/data/whispers.js',
  './src/meta/save.js',
  './engine/telemetry.js',
  './src/meta/cores.js',
  './engine/spawn.js',
  './engine/alarm-light.js',
  './src/meta/alarm-light.js',
  './src/meta/upgrades.js',
  './src/meta/modules.js',
  './src/meta/logs.js',
  './src/meta/whispers.js',
  './src/meta/behavior.js',
  './src/meta/boosts.js',
  './engine/cinematic.js',
  './src/meta/intro.js',
  './src/meta/hub.js',
  './engine/render-boundary.js',
  './engine/dungeon/topology.js',
  './engine/dungeon/reachability.js',
  './src/content/terminals.js',
  './src/content/weapons.js',
  './src/content/upgrades.js',
  './src/content/pickups.js',
  './src/content/projectiles.js',
  './src/content/music.js',
  './src/content/modifiers.js',
  './src/content/meta-save.js',
  './src/content/combo.js',
  './src/entities/room-index.js',
  './src/content/events.js',
  './src/content/shop.js',
  './src/content/perks.js',
  './src/content/effects.js',
  './src/content/hackware.js',
  './src/content/status.js',
  './src/content/lighting.js',
  './src/content/floor-generator.js',
  './src/content.js',
  './src/entities/source-metadata.js',
  './src/entities/spawn-table.js',
  './src/entities/enemy-stats.js',
  './src/entities/enemy-classification.js',
  './src/entities/spawn-modifiers.js',
  './src/entities/enemy-awareness.js',
  './src/entities/enemy-ability-tuning.js',
  './src/entities/player-perk-tuning.js',
  './src/entities/runtime-globals.js',
  './src/entities/runtime-collections.js',
  './src/entities/player-cheats.js',
  './src/entities.js',
  './src/entities/spawn-initializers.js',
  './src/entities/enemy-spawning.js',
  './src/entities/elite-affixes.js',
  './src/entities/status-effects.js',
  './src/entities/ai-helpers.js',
  './src/entities/architect-walls.js',
  './src/entities/beacons.js',
  './src/entities/crates.js',
  './src/entities/mines.js',
  './src/entities/shield-generators.js',
  './src/entities/wall-facing.js',
  './src/entities/security-systems.js',
  './src/entities/wall-turrets.js',
  './src/entities/field-effects.js',
  './src/entities/death-hooks.js',
  './src/entities/fuse-shards.js',
  './src/entities/render-passes.js',
  './src/entities/volatile-cores.js',
  './src/entities/combat-effects.js',
  './src/entities/deferred-spawns.js',
  './src/entities/shock-pulse.js',
  './src/render.js',
  './src/game.js',
];

const requiredPrecache = [
  './',
  './index.html',
  './privacy.html',
  './manifest.json',
  ...requiredInIndex,
  './assets/audio/title-theme.wav',
  './icon-192x192.png',
  './icon-512x512.png',
  './icon-192x192-maskable.png',
  './icon-512x512-maskable.png',
];

const noStore = [
  {
    path: './version.json',
    reason: 'Generated only in the GitHub Pages artifact by release-version.yml; keep it out of sw.js precache so the title screen fetch stays release-driven.',
  },
];

module.exports = {
  requiredInIndex,
  requiredPrecache,
  noStore,
};
